# Generated by Django 2.2 on 2021-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.TextField(),
        ),
    ]
